### ISSUE TITLE
[BUG][x.y.z] Unable to create Job 

### ISSUE THREAD

**Issue by jwestrmaier** [unofficial-memsource/memsource-cli-client#16] opened 2019-12-03 13:24 UTC
**Describe the bug**
Unable to create job because of invalid projectUid even if the projectUid exists
memsource job create --filenames csv_example.csv virt-who.xml --project-id s0sRdE0aIvzxLQfhGUEU6e

**Affected version**
0.3.1

**To Reproduce**
memsource job create --filenames csv_example.csv virt-who.xml --project-id s0sRdE0aIvzxLQfhGUEU6e

**Expected behavior**
A job is created.

**Screenshots or Traceback**
![image](https://user-images.githubusercontent.com/58473784/70054556-15bc4280-15d8-11ea-8fbd-fab4cefa548f.png)

**Comment by ludekjanda** [comment] 2019-12-03 13:44
Seems to be a duplicate of issue #17

**Closed as completed by ludekjanda** 2019-12-03 13:44 UTC
Labels: bug
